### PR TITLE
First pass at Auth

### PR DESCRIPTION
**Pull request by jjmountain**
Towards https://github.com/Wheely-Good/wheels-expo/issues/7

Adds Supabase, Zustand for global state management, useAuthStore hook, sign in / sign out pages. 

For now you need to confirm sign up via an email and we don't notify this.

### CODE REVIEW

**Comment by jjmountain** [comment]
Ok this is a big one. There does seem to be a bug sometimes with you not being able to navigate to the account page once signed in. We can probably merge for now and look at fixing that later though.

Btw you'll need to add a .env file and add some variables - I'll send them to you over chat now.

**Comment by jjmountain** [comment]
Ok so that bug might be affecting all the pages...

**Comment by hummus-erectus** [comment]
I just tried to sign up, there was an error but I was still redirected to the sign in page. I made a very short password but I can't find any currently implemented password validation.
Screenshot 2024-09-17 111235

**Comment by hummus-erectus** [comment]
Tried to sign up several times with different addreses and passwords. Each time the response from the server is as follows:

{"code":"over_email_send_rate_limit","message":"email rate limit exceeded"}

Explanation from docs:

"Too many emails have been sent to this email address. Ask the user to wait a while before trying again."

If I am supposed to be receiving a confirmation email, none of those have come through either...

**Comment by hummus-erectus** [comment]
I solved my issue, I needed to install the dotenv package to load the environment variables from .env into [process.env]

**Comment by hummus-erectus** [comment]
> Ok this is a big one. There does seem to be a bug sometimes with you not being able to navigate to the account page once signed in. We can probably merge for now and look at fixing that later though.
> 
> Btw you'll need to add a .env file and add some variables - I'll send them to you over chat now.

Once I finally logged in I was able to click around the pages as much as I wanted without issue so I have not been able to replicate this bug. On web. Were you also seeing this on web or on ios?

**Comment by jjmountain** [comment]
Did you look in the console for errors? They get logged there for now.

**Comment by jjmountain** [comment]
> Once I finally logged in I was able to click around the pages as much as I wanted without issue so I have not been able to replicate this bug. On web. Were you also seeing this on web or on ios?

That's fine then. I think if you log out and log in again you may have the issue, but this is something we can tackle later so if you agree could you approve this PR?

**Review by hummus-erectus — APPROVED** [review]
Seems good for now!

**Pull request merged**
