### PR TITLE
Change formatting of example question in app/index.tsx

### PR DESCRIPTION
**Pull request by hummus-erectus**
Update question formatting for clarity.

### CODE REVIEW

**Review by jjmountain — APPROVED** [review]
Nice improvement, and I didn't know about that JS method (will assume it works!)

Congrats on your first pull request! ㊗️ 🥳

**Comment by jjmountain** [comment]
@hummus-erectus do you see the button to squash and merge like this? If so go ahead and push it when ready 👍 

Screenshot 2024-09-14 at 16 39 12

**Comment by jjmountain** [comment]
that squashes all your commits into one commit that gets merged to the main branch (where the website is deployed from). Squashing is a good practice to follow to make the history of the main branch easier to read.

**Comment by hummus-erectus** [comment]
This is what I see:

Screenshot 2024-09-15 004122

So either I am looking in the wrong place, or this is due to the merge permissions setting you explained earlier?

**Comment by jjmountain** [comment]
Can you refresh github? I updated permissions so you should be able to

**Pull request merged**
