### PR TITLE
Move landing page components to files

### PR DESCRIPTION
**Pull request by hummus-erectus**
Created new folder for landing page components in component folder and moved PricingCard and FeatureCard to it. Broke down the LandingPage return function into components and moved to the same folder

### CODE REVIEW

**Comment by hummus-erectus** [comment]
Should the LandingPage function be in a separate file, for better naming? What is the best practice for the index.tsx file?

Should we also break up the Header component into smaller components or would that be too much componentization?

**Comment by jjmountain** [comment]
Yeah so I've actually already put LandingPage in it's own file. We also definitely want to break up all those components in that file and put them in components/LandingPage (I was just too lazy to do it yet).

**Comment by jjmountain** [comment]
This is all great work btw! 🤩 

I'm going to make a couple of changes to this PR which will make it much easier to merge with mine. Mainly renaming the main file to LandingPage because I've done that in the next PR already and it will make it easier to merge that one.

**Comment by jjmountain** [comment]
Scrap that. Let's just go ahead and merge!!

I'm going to merge this one for you so I can immediately rebase my one from main so I have your changes.

**Comment by jjmountain** [comment]
💣 💣 💣

**Comment by hummus-erectus** [comment]
Great! I'll delete the branch.

**Pull request merged**
