### PR TITLE
Make SVGs compatible for Android

### PR DESCRIPTION
**Pull request by hummus-erectus**
- Ensure that all icons are imported from lucide-react-native and not lucide-react
- Update styling for affected icons
- Install react-native-svg to avoid future issues with svgs

### CODE REVIEW

**Comment by hummus-erectus** [comment]
I have not been able to test this on iOS but in theory it should decrease rather than increase the likelihood of bugs related to svgs or icons. Fixes critical error on Android.

**Comment by jjmountain** [comment]
Ok great, I'll take your word on this for now as I don't have android up to test.

Btw I understand why you started this branch off the Auth one but because the work isn't really related it would make more sense to do it off the main branch. Then if I merge Auth, you can rebase this one from the new main branch and push it.

It might _sound_ like this is the same, but if I pushed more commits to Auth then this one would end up not having some of those commits so it would still be behind.

**Comment by jjmountain** [comment]
Ah ok I know what's happened. I squashed my commits into one commit which got merged to main when we merged the Auth branch so this has confused github which thinks that those commits of mine are commits we don't have on main (but actually they are, just as a squashed commit). Hence if you look at files changed you see ones which actually haven't changed on main (attached a photo so you can see as this will be gone after I rebase)

Screenshot 2024-09-17 at 21 51 41


I know this is quite confusing but it's another reason it's good to always make your branches off main / master. I'm going to rebase this one to remove my commits so we only have the stuff you changed. I'll do the same to your other PR.

**Review by jjmountain — APPROVED** [review]

**Comment by hummus-erectus** [comment]
Thank you, so as a rule make changes on a different branch (to what you are working on). I can't remember exactly what was my thought process at the time but I didn't yet know what the issue was and whether it was caused by some new update in the auth branch so it was probably something along those lines. Thanks for rebasing and getting the svg fix in there.

**Comment by hummus-erectus** [comment]
Sorry, I'm confused as main does not include the svg fixes after all (I still see lucide-react imports and not lucide-react-native components). So those svg-related updates have not been merged?

**Review by hummus-erectus — COMMENTED** [review]
I think I need to review these changes too? Here goes.

**Comment by hummus-erectus** [comment]
Sorry, still confused. It says you approved the changes but that somone other than you needs to review? 

Screenshot 2024-09-18 114729

**Comment by jjmountain** [comment]
> Thank you, so as a rule make changes on a different branch (to what you are working on)

Yeh you should never make changes to my branch, unless you're actually going to push them to the same pull request. What it looks like you did in this case was checkout a branch while you were on my branch (am I right?). 

The thing you should do is check out a new branch from the latest main branch. Let's just say to always do that for now as it's much less complicated.

**Comment by jjmountain** [comment]
> Sorry, I'm confused as main does not include the svg fixes after all (I still see lucide-react imports and not lucide-react-native components). So those svg-related updates have not been merged?

Why would you expect to see those svg-updates on main? THIS is the PR that is making that change is it not?

Perhaps you don't understand how the files changed tab works at the top. As you can see 'lucide-react-native' is in green which means this PR adds that line.

Screenshot 2024-09-18 at 8 59 56

**Comment by jjmountain** [comment]
> Sorry, still confused. It says you approved the changes but that somone other than you needs to review?

That's because you closed the PR and then re-opened it. You should generally not do this unless you are absolutely sure you don't want to merge the changes. I'm not sure why you did this but next time don't! 😄

**Comment by jjmountain** [comment]
Revisiting my comments on this it looks like I might have bene the one who didn't include some of your updates when I was rebasing from before 🤦 

Shall we get this one merged @hummus-erectus ? :)

**Comment by hummus-erectus** [comment]
Sure that would be great (I'm currently having to include the update locally to test Android). As you said I prematurely closed and reopened this though, and GitHub still says someone other than you needs to review and I already have reviewed. Seems like a dead end. Am I missing something or is the only option to redo the pull request? I can do one based on Main rather than the Auth branch if necessary.

**Comment by jjmountain** [comment]
Ah I see, I am not supposed to approve because I was the last committer but I have set it up so I can bypass that.

**Comment by hummus-erectus** [comment]
Thank you!

**Pull request merged**
